### ISSUE TITLE
generate-api-lib-sources fails in NX 20 due to deprecated property

### ISSUE THREAD

**Issue by Eagle-Tim** [driimus/nx-trumbitta#5]
Running the generate-api-lib-sources executor, when nx 20 is being used, results in an error "Cannot read properties of undefined (reading 'projects')"

This may be due to an undocumented breaking change, where the "workspace" property has been removed from the Executor Context. (See https://github.com/nrwl/nx/issues/28461)

This would affect the following line:

https://github.com/driimus/nx-trumbitta/blob/ce1a878ff3bb969d8d1f5445a06459cc9e7c3790/packages/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.ts#L11

It worked fine in nx 19

**Comment by Eagle-Tim** [comment]
The fix would be to replace "context.workspace" with "context.projectsConfigurations"

**Comment by amazing4u** [comment]
Thank you for fixing this. I can confirm, now it works

**Comment by driimus** [comment]
Thanks for reporting! For some reason I wasn't watching my own repo so I completely missed this issue when it was opened.

For anyone landing here, [v3](https://www.npmjs.com/package/@driimus/nx-plugin-openapi/v/3.0.0) supports nx@^20.
