### ISSUE TITLE
support `nx add @driimus/nx-plugin-openapi`

### ISSUE THREAD

**Issue by Tungsten78** [driimus/nx-trumbitta#7]
The standard way to add plugins is via [add](https://nx.dev/nx-api/nx/documents/add).

Doing so in nx 20, this plugin yields an error:
```
Error: Unable to resolve @driimus/nx-plugin-openapi:init.
Cannot find module './src/generators/init/schema.json'
```

It appears the schema is now required?

**Comment by driimus** [comment]
Thanks for reporting. Should be fixed in [v3.0.1](https://github.com/driimus/nx-trumbitta/releases/tag/v3.0.1).
